#!/usr/local/bin/python3
import json
import csv
import sys
import os
import multiprocessing



__author__ = 'Yacov Nagose'

# Variables
my_dict = []
csv_columns = []


def open_file(file):
    """
    This Function read the given file and updates
    the list my_dict and csv_columns with the needed values
    :return: None
    """
    with open(file, "r") as file:
        i = 0
        for line in file:
            my_dict.append(dict(json.loads(line)))
            if my_dict[i].keys() not in csv_columns:
                for key in my_dict[i].keys():
                    if key not in csv_columns:
                        csv_columns.append(key)
            i += 1


def write_file(path):
    """
    This Function creates a new file with the wanted name.
    Created CSV file and update the values in the CSV
    :return: None
    """
    write_path = path + '.csv'
    with open(write_path, "w+") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writeheader()
        for data in my_dict:
            writer.writerow(data)
    print("File successfully created under the name >> {}".format(write_path))


def run_app():
    read_path = []
    w_path = []
    jobs = []
    w_jobs = []
    logs = [f for f in os.listdir(path) if f.endswith('.log')]  # Ignore hidden files
    for log in logs:
        w_path.append(csv_file + log.replace('.log', ''))
    for index in range(len(logs)):
        read_path.append(path + logs[index])
    for i in range(len(logs)):
        rp = multiprocessing.Process(target=open_file, args=(read_path[i],))
        jobs.append(rp)
        rp.start()
        wp = multiprocessing.Process(target=write_file, args=(w_path[i],))
        w_jobs.append(wp)
        wp.start()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please enter file or folder name")
    else:
        path = sys.argv[1]
        if os.path.isfile(path):
            print("Path type is file")
            try:
                # run_app()
                open_file(path)
                print("Opening the file {}".format(path))
                write_file(path)
            except FileNotFoundError:
                print("File not found, Make sure the file name is correct")
                exit()
            except KeyboardInterrupt:
                print("Ok, I'm stopping.")
        if os.path.isdir(path):
            print("Path type is directory")
            try:
                csv_file = path + 'csv/'
                os.mkdir(csv_file)
                path = csv_file
            except OSError:
                print("Creation of the directory %s failed" % csv_file)
            else:
                print("Successfully created the directory %s " % csv_file)
            try:
                run_app()
            except FileNotFoundError:
                print("File not found, Make sure the file name is correct")
                exit()
            except KeyboardInterrupt:
                print("Ok, I'm stopping.")


