#!/usr/local/bin/python3
import json
import csv
import sys

# Variables
my_dict = []
csv_columns = []


def open_file():
    """
    This Function read the given file and updates
    the list my_dict and csv_columns with the needed values
    :return: read_path
    """
    read_path = sys.argv[1]
    with open(read_path, "r") as file:
        i = 0
        for line in file:
            my_dict.append(dict(json.loads(line)))
            if my_dict[i].keys() not in csv_columns:
                for key in my_dict[i].keys():
                    if key not in csv_columns:
                        csv_columns.append(key)
            i += 1
    return read_path


def write_file():
    """
    This Function creates a new file with the wanted name.
    Created CSV file and update the values in the CSV
    :return: None
    """
    write_path = open_file() + '.csv'
    with open(write_path, "w+") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writeheader()
        print("Creating the file..")
        for data in my_dict:
            writer.writerow(data)
    print("File successfully created under the name >> {}".format(write_path))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please enter file or folder name")
    else:
        try:
            open_file()
            print("Opening the file {}".format(sys.argv[1]))
            write_file()
        except FileNotFoundError:
            print("File not found, Make sure the file name is correct")
            exit()
        finally:
            print("Thanks for using this tool")

